### ISSUE TITLE
安装依赖包报错

### ISSUE THREAD

**Issue by MlsyrCc** [SuMaiKaDe/jddockerbot#19]
![Z~X@IUF Y$(6 1TJXHQ_ROD](https://user-images.githubusercontent.com/72785068/116501910-a8a00000-a8e4-11eb-8cca-202b1de21699.png)

**Comment by SuMaiKaDe** [comment]
哪里报错了？

**Comment by MlsyrCc** [comment]
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/include/python3.8/UNKNOWN
sysconfig: /usr/include/python3.8
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
这个不是吗？

**Comment by SuMaiKaDe** [comment]
@MlsyrCc 不是

**Comment by MlsyrCc** [comment]
那这个有报错吗？botrun.log
2021-04-29 15:00:13,736-telethon.network.mtprotosender-INFO=> [_connect] Connecting to 149.154.167.51:443/TcpFull... 
2021-04-29 15:00:13,760-telethon.network.mtprotosender-INFO=> [_connect] Connection to 149.154.167.51:443/TcpFull complete! 
Traceback (most recent call last):
  File "/jd/config/botV4.py", line 54, in <module>
    client = TelegramClient('bot', api_id, api_hash,
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

**Comment by SuMaiKaDe** [comment]
@MlsyrCc api填写不正确

**Comment by MlsyrCc** [comment]
感谢老哥，没想到是API问题，人都傻了，没往那方向去想，格式对的，好像漏复制1位
