### ISSUE TITLE
使用V4内置的bot，/snode命令报错

### ISSUE THREAD

**Issue by liyiecho** [SuMaiKaDe/jddockerbot#34]
发送/snode后
![image](https://user-images.githubusercontent.com/5213722/118129877-522bd900-b42f-11eb-9e10-5fcea0f4b7d0.png)

选scripts正常，但选own却报错，错误内容为
```
something wrong,I'm sorry
'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```
![photo_2021-05-13 21 04 17](https://user-images.githubusercontent.com/5213722/118129559-e8133400-b42e-11eb-9bad-c4eb616fddc3.jpeg)

这是run.log中报错的部分
```
2021-05-13 20:57:27,861-jbot-ERROR=> [nodebtn] something wrong,I'm sorry
'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
2021-05-13 20:57:27,861-telethon.client.updates-ERROR=> [_dispatch_update] Unhandled exception on mysnode
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "/jd/jbot/bot/snode.py", line 17, in mysnode
    if filelist.startswith('CMD-->'):
AttributeError: 'NoneType' object has no attribute 'startswith'
2021-05-13 20:59:22,201-jbot-ERROR=> [nodebtn] something wrong,I'm sorry
'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
2021-05-13 20:59:22,201-telethon.client.updates-ERROR=> [_dispatch_update] Unhandled exception on mysnode
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "/jd/jbot/bot/snode.py", line 17, in mysnode
    if filelist.startswith('CMD-->'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

![image](https://user-images.githubusercontent.com/5213722/118129639-01b47b80-b42f-11eb-8877-8a2f6398f9e2.png)

**Comment by SuMaiKaDe** [comment]
这是某个.js结尾的文件不能读取
