### ISSUE TITLE
telegram通知发送失败

### ISSUE THREAD

**Issue by WinterBoring** [SuMaiKaDe/jddockerbot#42]
RequestError: getaddrinfo EAI_AGAIN api.telegram.org
at ClientRequest. (/jd/scripts/node_modules/got/dist/source/core/index.js:953:111)
at Object.onceWrapper (events.js:422:26)
at ClientRequest.emit (events.js:327:22)
at ClientRequest.origin.emit (/jd/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
at TLSSocket.socketErrorListener (_http_client.js:469:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
code: 'EAI_AGAIN',
timings: {
start: 1621053820393,
socket: 1621053820398,
lookup: 1621053825403,
connect: undefined,
secureConnect: undefined,
upload: undefined,
response: undefined,
end: undefined,
error: 1621053825408,
abort: undefined,
phases: {
wait: 5,
dns: 5005,
tcp: undefined,
tls: undefined,
request: undefined,
firstByte: undefined,
download: undefined,
total: 5015
}
}
}每次都显示通知失败！参数设置多次检查没问题，节点翻墙正常，并且换了四五个节点测试还是一样，容器，镜像删除，拉取重装五次以上，还是同样问题！请大佬帮忙看看，是什么原因！谢谢。用的nevinee的bot版

**Comment by SuMaiKaDe** [comment]
提错地方了，与本程序无关
