### ISSUE TITLE
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

### ISSUE THREAD

**Issue by Saber0517** [SuMaiKaDe/jddockerbot#59]
我的api_id 已经实用了双引号，但网上搜相关答案说是API_ID 超过5位才会出现的问题， 我的api id 的确已经到达了7位
```java

nohup: ignoring input
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 55, in <module>
    jdbot = TelegramClient('bot', api_id, api_hash,
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)


```

**Comment by SuMaiKaDe** [comment]
@Saber0517 api或者hash无效，自己核对一下吧

**Comment by Saber0517** [comment]
@SuMaiKaDe  谢谢提醒，可以close了。具体原因是应该去到mapping config目录下去改bot.json -(v /C/QL/config:/ql/config)而不是在jbot的目录下加
